# Generated by Django 4.0.6 on 2022-09-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardGamesAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_friend_list',
            name='Last_Seen',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='t_friend_list',
            constraint=models.UniqueConstraint(fields=('user1_id', 'user2_Id'), name='cant be your own friend'),
        ),
    ]
